"""Rename name to repository

Revision ID: c68efcb783eb
Revises: 633cd507a8c0
Create Date: 2020-12-11 13:20:59.186114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68efcb783eb'
down_revision = '633cd507a8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('repository', sa.Text(), nullable=False))
    op.drop_column('project', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('name', mysql.TEXT(), nullable=False))
    op.drop_column('project', 'repository')
    # ### end Alembic commands ###
